### ISSUE TITLE
BUG: use `ruff check` now

### ISSUE THREAD

**Issue by prjemian** [davidslusser/actions_python_ruff#2]
[Workflow](https://github.com/BCDA-APS/apstools/blob/main/.github/workflows/code.yml) [failed](https://github.com/BCDA-APS/apstools/actions/runs/9701440832/job/26775095112?pr=966) here :
https://github.com/davidslusser/actions_python_ruff/blob/f7ddbbea442329acc72a18a4b37c68669a354d8d/action.yaml#L45

with this error:

```py
error: `ruff <path>` has been removed. Use `ruff check <path>` instead.
```

**Comment by prjemian** [comment]
```yaml
      - name: Run ruff
        uses: davidslusser/actions_python_ruff@v1.0.1
        with:
          python_version: "3.11"
```
